INSERT INTO Area (Name) VALUES ('Kitchen')
INSERT INTO Area (Name) VALUES ('Systems')
INSERT INTO Area (Name) VALUES ('Utility')
INSERT INTO Area (Name) VALUES ('Exterior')
INSERT INTO Area (Name) VALUES ('Outdoor')
INSERT INTO Area (Name) VALUES ('Bathroom')
INSERT INTO Area (Name) VALUES ('Surfaces')



INSERT INTO Inventory (Name, AreaId) VALUES ('Refrigerator',  1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Range',  1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Dishwasher', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Kitchen Sink', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Kitchen Cabinets', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Kitchen Countertops', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Garbage Disposal', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Wall Oven', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Cooktop', 1)
INSERT INTO Inventory (Name, AreaId) VALUES ('Furnace', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Boiler', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Cieling Fan', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Central AC', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Electrical', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Plumbing', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Ventilation', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Gas Fireplace', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Wood-burning Fireplace', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Smoke Detectors', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('CO Detectors', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Home Security', 2)
INSERT INTO Inventory (Name, AreaId) VALUES ('Washer', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Dryer', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Water Heater', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Water Filtration', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Water Softener', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Generator', 3)
INSERT INTO Inventory (Name, AreaId) VALUES ('Roof', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Gutters', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Foundation', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Siding', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Windows', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Front Door', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Back Door', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Sliding Door', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Garage Door', 4)
INSERT INTO Inventory (Name, AreaId) VALUES ('Driveway', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Walkway', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Lawn', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Deck', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Patio', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Fence', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Trees', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Plants', 5)
INSERT INTO Inventory (Name, AreaId) VALUES ('Toilet', 6)
INSERT INTO Inventory (Name, AreaId) VALUES ('Bathroom Sink', 6)
INSERT INTO Inventory (Name, AreaId) VALUES ('Bathroom Countertops', 6 )
INSERT INTO Inventory (Name, AreaId) VALUES ('Showerhead', 6)
INSERT INTO Inventory (Name, AreaId) VALUES ('Bath/Shower Surround', 6)
INSERT INTO Inventory (Name, AreaId) VALUES ('Bathroom Fan', 6)
INSERT INTO Inventory (Name, AreaId) VALUES ('Hardwood Flooring', 7)
INSERT INTO Inventory (Name, AreaId) VALUES ('Carpet Flooring', 7)
INSERT INTO Inventory (Name, AreaId) VALUES ('Tile Flooring', 7)
INSERT INTO Inventory (Name, AreaId) VALUES ('Stone Flooring', 7)
INSERT INTO Inventory (Name, AreaId) VALUES ('Vinyl/Laminate Flooring', 7)
INSERT INTO Inventory (Name, AreaId) VALUES ('Linoleum Flooring', 7)





INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Change water filter',1, 6, 'By removing the used filter and installing a new one, you can effeciently remove impurities from your tap water')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Dust condenser coils',1, 6, 'Removing dust from the coils allows for better airflow and cooling, which can extend the life of your fridge')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check the Gasket',1, 6, 'Cleaning the rubber seal around the perimeter of your fridge can help to maximize cooling power')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Degrease the controls',2, 6, 'This will help keep your controls from sticking or becoming loose')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Wipe down oven',2, 6, 'Scrub stuck on stains that can lead to smoke and lingering odors')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Deep clean cooktop',2,, 6, 'Typically using a single-edge razor can help to remove stuck on stains, apply a specialized cooktop cleaner to add a nice polish')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Degunk the door seal',3, 3, 'Find the seal around the perimeter and wipe down with vinegar or cleaing agent of your choice. This gunk and grime can lead to mold and leaks')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean the filter',3, 3, 'First remove the cylinder filter from the base of the machine, check for damage, rinse and wipe away any debris, and replace')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Remove hard-water residue',3, 3, 'Look for mineral deposits inside your machine, using a citric based dishawasher cleaner would be best used for this')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Contain leaks',4, 12, 'Check for tell-tale signs like a dripping faucet or water stains, leaks typical caused by an O-ring can hopefully be fixed with just a replacement')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Contain clogs',4, 12, 'Look for tell-tale signs of a clog, if necessary take some time to deal with potential clogs using a plunger or drain snake')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Do a deep clean',5, 12, 'Consider the finish of your cabinets, using a cleaning solution to remove dust and grime build up.')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repairs, as needed',5, 12, 'Check for things like loose door hinges, and shelves. By keeping screws tightened, you can help extend the life of your cabinets')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Do a deep clean',6, 3, 'Consider the finish of your countertops, using a mild soap and a soft sponge or cloth to prep the area and baking soda and water for tougher stains.')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repairs, as needed',6, 12, 'Check for things like loose door hinges, and shelves. By keeping screws tightened, you can help extend the life of your cabinets')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Review your heating bill',10, 12, 'It is important to look for irregularities in your heating bill that could mean your machine needs some repairs')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Change filters',10, 12, 'Regulary change the filter inside your furnace that helps to remove smoke, dust and other particles from the air in your home')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check registers and grilles',10, 12, 'These metal grates that cover the vent openings around your home help regulate airflow, if there are rooms you that dont get used as much, manually close the registers for better airflow')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Reverse direction',12, 6, 'It is important to reverse the direction of your ceiling fan based on the time of year, counterclockwise in the summer creats a cooling breeze, and clockwise in the winter to help circulate warm air by creating an updraft')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Wipe down fan',12, 3, 'Ceiling fans are notorious for collecting dust particles, by wiping down the fans blades and down to the base you can avoid particles recirculting in your home')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Change filters',13, 2, 'Remove trapped pollutants, leading to better air quality, by installing a new filter in the intake vent ')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check registers and grilles',13, 12, 'These metal grates that cover the vent openings around your home help regulate airflow, if there are rooms you that dont get used as much, manually close the registers for better airflow')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Review your cooling bill',13, 12, 'It is important to look for irregularities in your cooling bill that could mean your machine needs some repairs')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('De-grime and deodorize',7, 1, 'Prevent food and waste build up, that may lead to bad odors, either a cleaning solution or ice and baking soda')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean splash guard',7, 6, 'Gunk can also build up under the splash guard in your sink, remove the rubber panel or clean while in place with a wet rag')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Degrease the controls',8, 6, 'This will help keep your controls from sticking or becoming loose')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Wipe down oven',8, 6, 'Scrub stuck on stains that can lead to smoke and lingering odors')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Degrease the controls',9, 6, 'This will help keep your controls from sticking or becoming loose')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean the filter',9, 3, 'First remove the cylinder filter from the base of the machine, check for damage, rinse and wipe away any debris, and replace')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Review heating bill',11, 12, 'Look for mineral deposits inside your machine, using a citric based dishawasher cleaner would be best used for this')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check registers and grilles',11, 12, 'These metal grates that cover the vent openings around your home help regulate airflow, if there are rooms you that dont get used as much, manually close the registers for better airflow')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Change filters',11, 1, 'Regulary change the filter inside your boiler that helps to remove smoke, dust and other particles from the air in your home')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Do a saftey check',14, 12, 'Take some time to open up your electrical panel, looking for any signs of corrosion')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Review safety shut off plan',15, 12, 'This is especially important for new installs and replacements, make sure you have a plan for if a pipe burst')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Prepare for cold snap',15, 12, 'It is very important in the winter months to avoid frozen pipes by allowing warm air to circulate near them, letting cold water drip, or simply keeping the heat on in your home while away')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repairs, as needed',28, 6, 'Check for things like loose shingles, and water damage. If you dont have easy roof access call a license professional')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Get a tune up',16, 12, 'annual maintainance of the ventilation system, can help to extend life and effectivness')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Do a safety check',17, 12, 'You should primarily focus on checking the safety barrier mesh for holes or exposed areas')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Get a tune up',17, 12, 'annual maintainance of the ventilation system, can help to extend life and effectivness')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Do a safety check',18, 12, 'You should primarily focus on checking the safety barrier mesh for holes or exposed areas')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Get a tune up',18, 12, 'annual maintainance of the ventilation system, can help to extend life and effectivness')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Test detectors',19, 3, 'Testing the smoke detector is very simple and important in making sure it works how it should')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Test detectors',20, 3, 'Quickly test your detetectors, following the steps of you instruction manual')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Vacuuming',52, 3, 'Get rid of pet hair and dust particles that are trapped in deep inside the carpet')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Sweeping and mopping',53, 1, 'Easily take care of dust and grime build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repairs as need',55, 6, 'Check for loose or damage boards and replace as needed')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Sweeping and mopping',55, 1, 'Easily take care of dust and grime build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Sweeping and mopping',56, 1, 'Easily take care of dust and grime build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Shampooing/deoderizing',52, 3, 'Remove trapped odors by running a shampooer or spread some baking soda on the floor to deoderize')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Sweeping and mopping',51, 1, 'Easily take care of dust and grime build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repairs as need',51, 6, 'Check for loose or damage boards and replace as needed')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Dust sensors',21, 6, 'Quickly duting the sensors will make sure they are working effeciently, and not overheating')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check for updates',21, 3, 'If your system doesnt update automatically, manually checking and installing them can help your device run as it should')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Test',21, 12, 'You want to make sure your system is functioning properly')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect the hoses',22, 3, 'Behind the washer, make sure the hoses have no bulges or cracks that could lead to a leak')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean the interior',22, 3, 'You can easily clean the inside of your machine by running a cycle without any clothes')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Wipe down the gasket',22, 6, 'Open the door to the machine, and wipe beneath the rubber lining on the door')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Deep clean lint screen',23, 3, 'While it is important to remove dust after each load, do a deep clean with soap and warm water to prevent stuck on build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Drain and wash out sediment',24, 6, 'Drain water inside your tank, and then begin turning on and off cold water to rinse away sediment')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean gutters',29, 6, 'Use a ladder to take a look down inside your gutters and remove any build up')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check for cracks',30, 12, 'Check all areas of foundation surrounding your home and look for any cracks or damage that could be a sign or lead to water damage')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repair as needed',31, 12, 'Look for any loose siding, if you can reach it with a ladder and its still usable reinstall using strong nails')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Clean window tracks',32, 3, 'Dust can build up and not allow windows slide properly, you should wipe these down frequently')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Check window surround/glass',32, 12, 'Caulking around the window help prevent water from getting in your home, check for any damaged caulking and any damage you may have missed on the glass')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Tighten locks',33, 6, 'Over time your door locks and handle may become loose, you should try and tighten these to make sure the door stays secure')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect hardware',36, 6, 'With regular use of the garage door, making sure no hardware is loose can ensure safe use')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Test and balance',36, 12, 'A general safety test, listening or noticing any possible hazards can help you pin point issues with your garage door')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect and clean',37, 3, 'Keeping your driveway as free from debris as possible can extend the life, look for any signs of cracks or water build up spots')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot clean',40, 3, 'Using a power washer can effeciently remove stuck on stains')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot clean',41, 3, 'Using a power washer can effeciently remove stuck on stains')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Spot repair as needed',42, 6, 'Check for any loose or damaged boards and replace them with a new board as quickly as you can to prevent further damage to the fence')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Trim',43, 12, 'Trim back branches and leaves to prevent overgrowth or call in a professional to have it done')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Prune',44, 12, 'Trimming the dead leaves from your plants can make them look more appealing and offer an extended life')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect',45, 6, 'Check the caulk around the base, and the hardware in the back for any damage, or a loose O-ring')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Mulch',44, 6, 'Add new mulch will allow your plants to absorb moisture better and provide an overall better quality of life')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Disenfect and clean',45, 3, 'Deep clean using a bathroom cleaning agent, checking for any signs of clogs and remedy those as well')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('De-clog',46, 6, 'You can use a store bought declogging liquid and/or snake like tools to remove any build up in your sinks drain')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect caulking',47, 6, 'The caulk around your countertop prevents water damage, over time the caulk may become worn and need replaced')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Change filter',48, 3, 'Chaning the filter in your showerhead can ensure harmful elements are removed from your water system')
INSERT INTO Upkeep (Title, InventoryId, NumberOfMonths, Description) VALUES ('Inspect',48, 6, 'If your shower head is loose or build up occurs, it can lead to reduce pressure. If you can clean and/or tighten it, you can ensure effenciency')
